name: Backend
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - run: gofmt -l -d .

  vet:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - run: go vet ./...

  test:
    strategy:
      matrix:
        include:
          - os: Ubuntu
            version: 22.04
          - os: macOS
            version: 12
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    name: Run Go tests (${{ matrix.os }} ${{ matrix.version }})
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - run: go mod download
      - run: go run ./internal/cmd/pretestsetup
      - run: go test -v -race ./...
