name: Frontend
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc
      - run: cd frontend && npm ci && npm run lint

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc
      - name: Run npm ci
        run: cd frontend && npm ci
      - name: Install Playwright Browsers
        run: cd frontend && npx playwright install --with-deps
      - name: Run tests
        run: cd frontend && npm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
