name: "Lint node.js project"
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        run: NVMRC=$(cat frontend/.nvmrc)
        id: nvmrc
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.NVMRC }}"
      - run: cd frontend && npm ci && npm run lint
